Milestone 2: Queried and updated animals table in Vet clinic database
prg-04/Vet_Clinic pull request #2
Opened 2023-09-29 06:02 UTC by prg-04

### I have done the following to reach this milestone:

- Updated table using transactions
- Used aggregate functions to write queries 

- Screenshots

- [ ] Add a column species of type string to your animals table.
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/bbff610e-43e3-4227-9801-92ee60aa9a21)

- [ ] Inside a transaction update the animals table by setting the species column to unspecified. Verify that change was made. ![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/da2730f2-575b-4dfa-859b-9c2b51d059f0)

- [ ] Inside a transaction:
     - [ ] Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
     - [ ] Update the animals table by setting the species column to pokemon for all animals that don't have species already set.     
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/bb8e9f8c-f046-4162-8059-96e147a9befb)

- [ ] Inside a transaction delete all records in the animals table, then roll back the transaction.

![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/fc1dc3e4-1a92-4bf9-bb3e-f8699a2744dc)
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/e5dd568e-f280-4f82-a588-427d00fc06f7)

- [ ] Inside a transaction:
    - [ ] Delete all animals born after Jan 1st, 2022.
    
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/6a5dd34e-72c6-4d3a-907e-f0bdc2a61fc5)

- [ ] Update all animals' weight to be their weight multiplied by -1.
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/f8e7542f-06db-413c-a350-4a4800753644)

- [ ] Update all animals' weights that are negative to be their weight multiplied by -1.
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/75bcf062-e20c-4118-b4fe-350308b59b8a)

- [ ] How many animals are there?
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/ad776634-dc53-4e9d-a989-1cf444e053b9)

- [ ] How many animals have never tried to escape?
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/aaac5128-6a16-454f-b87e-545af0bb42ab)

- [ ] What is the average weight of animals?
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/06c9ea6f-31e5-4307-a512-7a9ccc78d755)

- [ ] Who escapes the most, neutered or not neutered animals?
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/07eb9599-8420-45a4-bb52-9462d4158214)

- [ ] What is the minimum and maximum weight of each type of animal?
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/d0cdc303-d19d-4dda-908c-26c0b2ac6af3)

- [ ] What is the average number of escape attempts per animal type of those born between 1990 and 2000?
![image](https://github.com/prg-04/Vet_Clinic/assets/103628308/6f874084-a923-4f7f-8ff5-84bae01b6eb6)

2023-09-29 07:01 UTC, Bantealem requested changes
# Status: Change Required
Hi @prg-04, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Correct Git flow
- [x] Professional Readme
- [x] Descriptive PR summary

## Required Changes ♻️
- [ ] Please make a transaction to delete all animal data. Currently, I can't find it `queries.sql `file. Kindly, add it.
![image](https://github.com/prg-04/Vet_Clinic/assets/101523582/704b510a-1412-4c9e-9321-046327c6748f)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 07:01 UTC, Bantealem commented on schema.sql
> +COMMIT;
Great job so far. Kindly remove the above transaction code except for lines 15 and 16 since you have already make it in `queries.sql` file. kindly fix it.
![image](https://github.com/prg-04/Vet_Clinic/assets/101523582/3dfca9b0-0698-4a8b-afc0-38bd05cfedd3)

2023-09-29 07:01 UTC, Bantealem commented on queries.sql
> +SET species = 'Unspecified';
Great job so far. Please verify whether changes are made or not in your transaction.  Currently, you didn't `ROLLBACK` the transaction. For example you can add the following
  `SELECT species from animals; `
   `ROLLBACK;`
`SELECT species from animals;`
![image](https://github.com/prg-04/Vet_Clinic/assets/101523582/fa9f1388-fdd5-46ec-88e0-ed382ba71c3d)

2023-09-29 07:01 UTC, Bantealem commented on queries.sql
> +
Great job so far. Please verify whether the change was made or not. Currently, you are not verifying the transaction before and after `Commit`. You can check simply by adding  `SELECT species from animals;` before and after `commit`. Kindly, fix it.
![image](https://github.com/prg-04/Vet_Clinic/assets/101523582/9bf58757-cd19-48e6-aa29-86624ef4f6cc)

2023-09-30 05:59 UTC, 1GORDON requested changes
##
## Hi @prg-04 ✋

Good job so far!

## Highlights!
- Added screenshots to the pull request description ✔️ 
- Implemented requested changes ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 05:59 UTC, 1GORDON commented on queries.sql
> +COMMIT;
Great job @prg-04 🤝

- [ ] As stated by the previous reviewer, kindly verify whether the change was made or not. You never verified the changes before and after the commit. Don't forget to update your results in the screenshots.
![transaction-1](https://github.com/prg-04/Vet_Clinic/assets/63917725/5d9ab7ec-7cda-41cb-abe0-36b1fc65795a)

2023-09-30 05:59 UTC, 1GORDON commented on queries.sql
> +SELECT species FROM animals;
Great job @prg-04 🤝

 As stated by the previous reviewer, kindly verify whether the change was made or not. You never verified the changes before the rollback. Don't forget to update your results in the screenshots.
![transaction-2](https://github.com/prg-04/Vet_Clinic/assets/63917725/30b3abd9-1f9a-4d9c-a854-cb0415b3537d)

2023-09-30 07:19 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @prg-04 , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Fixed issue
✅ ... Good commit messages

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 04:23 UTC, merged